export const ferryRoutes = {
 TSAWASSEN: "TSA",
 SWARTZ_BAY: "SWB",
 SOUTHERN_GULF_ISLANDS: "SGI",
 DUKE_POINT: "DUK",
 SALTSPRING_ISLAND: "FUL",
 HORSESHOE_BAY: "HSB",
 NANAIMO: "NAN",
 LANGFORD: "LNG",
 BOWEN_ISLAND: "BOW",
}
